metal:
  children:
    masters:
      hosts:
        metal0: {ansible_host: 192.168.0.18, mac: '2e:41:de:0e:3e:22', disk: sda, network_interface: eth0}
        metal1: {ansible_host: 192.168.0.19, mac: 'aa:30:8e:5a:ee:16', disk: sda, network_interface: eth0}
        metal2: {ansible_host: 192.168.0.20, mac: '86:46:30:3d:b6:15', disk: sda, network_interface: eth0}
    workers:
      hosts:
        metal3: {ansible_host: 192.168.0.22, mac: '1e:d2:11:b6:97:a2', disk: sda, network_interface: eth0}
